### ISSUE TITLE
Lilypond noty na mobilu nejsou na celou šířku displeje

### ISSUE THREAD

**Issue by michaeldojcar** [glowspace/proscholy-web#44]
![IMG_DF47FAB1DAD3-1](https://user-images.githubusercontent.com/1665018/143595932-ccdeea48-6b74-468c-ac5f-610e26769453.jpeg)

**Comment by vitkolos** [comment]
https://glowspace.atlassian.net/browse/ZPS-276

**Comment by vitkolos** [comment]
Teď jsem to vyzkoušel na Androidu a vypadá to, že už to funguje v pořádku.
