### ISSUE TITLE
Špatný liturgický den v Co hrát na mši

### ISSUE THREAD

**Issue by michaeldojcar** [glowspace/proscholy-web#53]
Vypadá to, že kalendář je o týden posunutý.

<img width="738" alt="Snímek obrazovky 2022-01-26 v 18 53 28" src="https://user-images.githubusercontent.com/1665018/151219381-19d5dfe8-33f2-4cba-9e70-48ec951f29fb.png">

<img width="313" alt="Snímek obrazovky 2022-01-26 v 18 54 44" src="https://user-images.githubusercontent.com/1665018/151219401-a99c42cb-143b-43ed-b19b-2ed88e39628b.png">
.

**Comment by thes01** [comment]
Jo, vypadá to, že všechny neděle jsou posunuté o jedno.. nepozornost při exportu.
