### ISSUE TITLE
Smart link banner pro iOS

### ISSUE THREAD

**Issue by michaeldojcar** [glowspace/proscholy-web#67]
Podle https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners#3701575.

**Comment by michaeldojcar** [comment]
Tak už to tam mám, ale neukazuje se mi to. @Paprikadobi Fakt stačí dát tam ten meta tag?

**Comment by Paprikadobi** [comment]
Ještě by měl být na webu publikovaný soubor `apple-app-site-association` [universal links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html). A pak předpokládám budu muset ještě u sebe v aplikaci přidat nějaké informace, aby apple věděl, že to je propojené.

**Comment by Paprikadobi** [comment]
tak teď jsem si zkusil udělat jednoduchou stránku, kam jsem dal jen ten tag a funguje to teda a nic dalšího potřeba není.

**Comment by michaeldojcar** [comment]
A na https://staging.zpevnik.proscholy.cz ti to jede? Mně ne, ale ten meta tag tam vidím. Kdyžtak mrkni, zda ho mám správně.

**Comment by Paprikadobi** [comment]
Ne, ale máš tam `property="apple-itunes-app"` a mělo by to být `name="apple-itunes-app"`.

**Comment by michaeldojcar** [comment]
Hotovo. :-) Pak už jen vymyslet, aby to linkovalo podle té navigace. Když jsem na webu na písni, tak aby to v appce otevřelo už tutéž píseň.

**Comment by Paprikadobi** [comment]
Tak na to tam bude ten `app-argument=url`, tu novou verzi jsem dělal tak, že mám pravě navigaci už podle url, takže když mi to tam přidáte, tak nebude problém navigovat podle toho.

**Comment by michaeldojcar** [comment]
Ok, založil jsem na to nový issue: https://github.com/glowspace/proscholy-web/issues/70
